name: re4_topdwn
description: "A top-down video game project using Flutter and Flame."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version and build number for the application
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.5.0
  flame_tiled: ^1.5.0
  flutter_svg: ^2.0.14
  flame_audio: ^2.10.5
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   # Linting package for good coding practices

flutter:
  uses-material-design: true

  # Assets section for images, audio, and other assets
  assets:
    - assets/tiles/indoor_level.tmx
    - assets/tiles/re_indoors.tsx
    - assets/tiles/wood_paneling.tsx
    - assets/images/interior.png
    - assets/images/town_buildings.png
    - assets/images/player_walk_sprite.png
    - assets/images/player_idle_sprite.png
    - assets/images/player_shoot_sprite.png
    - assets/images/player_death_sprite.png
    - assets/images/enemy_walk_sprite.png
    - assets/images/enemy_attack_sprite.png
    - assets/images/enemy_death_sprite.png
    - assets/images/enemy_idle_sprite.png